os: osx
dist: focal
language: python

jobs:
  - os: osx
    language: shell
    
install:
  - python3 -m pip install cibuildwheel==1.12.0
  
script:
  - python3 -m cibuildwheel --output-dir wheelhouse
